### PR TITLE
Update to reader.py for issue #35

### PR DESCRIPTION
**Pull request by ggirelli**
Proposed change according to issue #35 . Basically, the default `init` method of `ND2Reader` would now require a file handler (`io.*`) and there is a staticmethod (`from_file`) that reproduces the original behavior. What do you think? Is this an acceptable approach? Any alternative approaches? 

Also, I am not sure but at a first glance it looks like the `filename` attribute of `ND2Reader` is never used anywhere else. If it is, I'd need to fix it. Please, let me know :smile:

### CODE REVIEW

**Comment by rbnvrw** [comment]
Hi @ggirelli thanks a lot for sending this PR. I think it goes into the right direction but I have two requests:

1. I'd really like to make this backwards compatible / non-API breaking. So I propose we check if `fh` is a `str`, then treat is as a filename, and otherwise treat it as a file handler. 
2. Related to that: can you add a unit test to check if it correctly opens the file, both when a filename is passed or a file handler is passed?

Other than that I think it is a nice addition :+1:

**Comment by ggirelli** [comment]
Hej @rbnvrw, thanks for the hints! I'll work on them next week :smile:

**Comment by ggirelli** [comment]
@rbnvrw hi! I have tried to follow your directions, let me know if this works for you :smile: 

Personally, I am not a huge fun of functions that allow an input argument to have potentially different types, but I understand that it is preferable to be as backward compatible as possible!

**Comment by rbnvrw** [comment]
I think it looks great! Thank you :+1:

**Comment by pmarks** [comment]
@rbnvrw this is a super handy fix for images on s3. Any chance of release including this change?

**Comment by rbnvrw** [comment]
Thank you for reaching out @pmarks I have been busy finishing my thesis but a release is planned in a few weeks!

**Pull request merged**
